services:
 rocketchat:
     image: rocket.chat:6.7
     restart: unless-stopped
     volumes:
     - ./uploads:/app/uploads
     environment:
     - PORT=3000
     - ROOT_URL=https://chat.codensmoke.com
     - MONGO_URL=mongodb://mongo:27017/rocketchat?replicaSet=rs0&directConnection=true
     - MONGO_OPLOG_URL=mongodb://mongo:27017/local?replicaSet=rs0&directConnection=true
     - Accounts_UseDNSDomainCheck=True
     # Until we update mongodb
     - BYPASS_MONGO_VALIDATION=true
     depends_on:
     - mongo
     expose:
     - 3000
     networks:
       - local
       - caddy-config_webtraffic
       - metrics_statstraffic

 mongo:
     image: mongo:5.0.3
     restart: unless-stopped
     command: mongod --oplogSize 128 --replSet rs0
     volumes:
     - data:/data/db
     - ./data/dump:/dump
     networks:
       - local

 # this container's job is just to run the command to initialize the replica set.
 # it will run the command and remove himself (it will not stay running)
 mongo-init-replica:
     image: mongo:4.0
     command: >
         bash -c "for i in `seq 1 30`; do
         mongo mongo/rocketchat --eval \"
             rs.initiate({
             _id: 'rs0',
             members: [ { _id: 0, host: 'localhost:27017' } ]})\" &&
         s=$$? && break || s=$$?;
         echo \"Tried $$i times. Waiting 5 secs...\";
         sleep 5;
         done; (exit $$s)"
     depends_on:
     - mongo
     networks:
       - local

 mongodb-exporter:
     image: bitnami/mongodb-exporter:latest
     restart: always
     expose: 
       - 9001
     networks:
       - local
       - metrics_statstraffic

networks:
  caddy-config_webtraffic:
    external: true
  metrics_statstraffic:
    external: true
  local:

volumes:
  data:
